// flow-typed signature: feeeea0298e746743ef519ccd765f741
// flow-typed version: <<STUB>>/big-integer_v^1.6.31/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'big-integer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'big-integer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'big-integer/BigInteger' {
  declare module.exports: any;
}

declare module 'big-integer/BigInteger.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'big-integer/BigInteger.js' {
  declare module.exports: $Exports<'big-integer/BigInteger'>;
}
declare module 'big-integer/BigInteger.min.js' {
  declare module.exports: $Exports<'big-integer/BigInteger.min'>;
}
